version: '3'
services:
  web:
    build: ../hatch-frontend/.
    ports:
     - "8080:80"
    environment:
      API_DOMAIN: hatch-api-1:3000
    depends_on:
      - api
  api:
    build: ../hatch-backend/.
    ports:
     - "3000:3000"
    environment:
      MONGO_HOST: hatch-mongo-1
      MONGO_USER: root
      MONGO_PWD: example
      MONGO_PORT: 27017
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0.6
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  apidoc:
    image: redocly/redoc:v2.0.0
    ports:
     - "8123:80"
    environment:
      SPEC_URL: api.yaml
    volumes:
      - ./api.yaml:/usr/share/nginx/html/api.yaml